### ISSUE TITLE
January iteration

### ISSUE THREAD

**Issue by mbest** [knockout/knockout#1267]
Agenda:

Ready for review/merge:
- [x] #1003 Observable template name evaluation could set observable
- [x] #1081 options caption always re-added when update binding fires
- [x] #1237 Improve '.toThrowContaining' matcher error message
- [x] #1234 Tidied up the different sets of native template tests into proper Jasmine groupings
- [x] #1272 Evaluate deferred computed on subscribe
