### ISSUE TITLE
February 2014 Iteration

### ISSUE THREAD

**Issue by mbest** [knockout/knockout#1298]
I'm disappointed that we covered so little last month. Let's see if we can make up for it this month. I'll start, though, with the remaining items from last month.
- [x] #647 Support select value not in options list, optionally
- [x] #1255 Track observables accessed in `getBindingAccessors`
- [x] #1199 Array performance optimizations
- [x] #627 Provide access to dependency count within computed function
- [x] #1209 evaluating a disposed deferred computed causes it to take dependencies
