### ISSUE TITLE
March 2014 planning

### ISSUE THREAD

**Issue by SteveSanderson** [knockout/knockout#1352]
As we discussed before, it would be great if we could kick off the journey towards 3.2 by making progress on the [proposed new features](https://github.com/knockout/knockout/issues/1273). This is a substantial bit of work and making time for it will mean we have less (perhaps very little) throughput on routine smaller enhancement and bugs. I think it will be worth it.

As a rough suggestion, we could approach it like this:
- [x] 1. Ensure we're satisfied with the [components spec](https://github.com/knockout/knockout/issues/1290). This has been discussed at length already and I think we're basically there already (let's not restart from scratch), but if there are final tweaks, now's a good time to know about them.
- [x] 2. Implement components
- [ ] 3. Set out a spec for the two other proposed items (string interpolation and custom elements) and confirm what we actually want
- [ ] 4. Implement whatever we decide

For the March iteration, I think we could aim to cover numbers 1 and 2. Any other smaller, separate enhancements/fixes would be a bonus. As for actually implementing number 2, I'm happy to take the bulk of that, but it's also up to @mbest if he wants to cover none/some/most/all of it!

@mbest / @rniemeyer - what do you think?
