### ISSUE TITLE
Issues clean up

### ISSUE THREAD

**Issue by paglias** [knockout/knockout#870]
I've explored more or less every issue reported on Github and found out a lot of bugs that are already fixed, are only waiting to be merged from a lot of months... and I came out with a list of about 30 issues that can be closed/merged:
## Issues that can be closed
- [x] #787 Jan/Feb 2013 iteration planning -> All the items have been completed
- [x] #522 take control of knockout npm package -> control taken
- [x] #751 Out of browser support and test runner -> implemented in the already merged #798 
- [x] #712 Non-browser environment -> previous request of #751 
- [ ] #764 Value binding not updating when clicking outside the document in Chrome/WebKit -> not related to Knockout, we can do nothing on that
- [x] #574 ks.toJSON will randomly fail in IE8 -> not Knockout's fault
- [x] #576 input[type=search] built in clear and valueupdate -> Not a bug
- [x] #642 Add a component.json file, so Knockout.js can register with the Bower package manager -> discussed in #646
- [x] #586 Added a stringContains method to utils.js -> there's a native method in javascript, see my comment to it
- [x] #526 npm package - client version possible? -> this will be fixed when we finish #866 and anyway Steve has already pushed a new version to NPM in the meantime
- [x] #55 ko.toJS and dates -> already fixed
## Bug fixes that can be merged without any side effect
- [x] #827 fixes #733 (observable array accepting non-array value)
- [x] #832 fixes #560 (a broken link in the documentation)
- [x] #829 fixes #691 (remove duplicate specs for checked binding)
- [ ] #555 Guard against arbitrary objects being passed in on subscribe
- [x] #828 fixes #703 (IE 9 frame bug with hasfocus binding)
- [x] #871 add null and undefined to js reserved words, fixes #762
- [x] #611 Replace stringTrimRegexp with a shorter and faster variant
## Changes that can be merged
- [x] #833 ko.toJS changes (fixes #577, #251, #524) -> more than a change it's a series of bug fixes, the only thing that could cause problems is that ko.toJS won't serialize anymore functions (#251). But i think it's safe to merge it 
- [ ] #845 Added method 'pushAll' into observableArray (fixes #416) -> This also hasn't any type of side effect 
- [ ] #480 Update to end comment regex to support the form 
- [ ] #720 Allow 'options' binding on `<datalist>` element

Here I've included only the ones I was sure about, there are others but I've preferred not to include them.

Also, I've noticed that a lot of issues are about the same bugs/feature requests, I think that when is possible we should try to track them in only one issue and close all the others.
