### ISSUE TITLE
May 2013 Iteration

### ISSUE THREAD

**Issue by mbest** [knockout/knockout#945]
Continuation of 2.3.0 and 3.0.0 development:

[2.3.0](https://github.com/SteveSanderson/knockout/issues?milestone=3&state=open) development task list:
- [x] #929 add optionsAfterRender
- [x] #486 fix compiler warnings
- [x] #970 fix exception in ko.computed read function kills the computed
- [x] #375 fix spaces around data-bind = in string templates
- [x] #973 Remove `checkedValue` binding

[3.0.0](https://github.com/SteveSanderson/knockout/issues?milestone=4&state=open) development task list:
- [x] #932 New interface for access to sibling bindings
- [x] #946 Separate computed observables for each binding
- [x] #950 Enable bindings to declare order dependencies
- [x] #954 Fix `checkedValue` behavior
