### ISSUE TITLE
3.0.0 Beta Release Planning

### ISSUE THREAD

**Issue by mbest** [knockout/knockout#988]
Tasks left to do:
- [x] #976 Merge 2.3.0 changes
- [x] #485 Support observable view models
- [x] #935 Fix change event notification in `options` binding
- [x] #1022 Node preprocessing
- [x] #1025 Merge remaining 2.3.0 changes
